// Generated by CoffeeScript 1.8.0
(function() {
  var FilterList, getFilter,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  getFilter = require('./scan').getFilter;

  module.exports = FilterList = (function() {
    function FilterList(operator, filter) {
      var _ref;
      this.operator = operator;
      this.get = __bind(this.get, this);
      this.addFilter = __bind(this.addFilter, this);
      if ((_ref = this.operator) !== 'MUST_PASS_ALL' && _ref !== 'MUST_PASS_ONE') {
        this.operator = 'MUST_PASS_ALL';
      }
      this.filters = [];
      if (filter) {
        filter = getFilter(filter);
        if (!filter) {
          return false;
        }
        this.filters.push(filter);
      }
    }

    FilterList.prototype.addFilter = function(filter) {
      filter = getFilter(filter);
      if (!filter) {
        return false;
      }
      return this.filters.push(filter);
    };

    FilterList.prototype.get = function() {
      return {
        operator: this.operator,
        filters: this.filters
      };
    };

    return FilterList;

  })();

}).call(this);
