// Generated by CoffeeScript 1.8.0
(function() {
  var Get,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  module.exports = Get = (function() {
    function Get(row) {
      this.row = row;
      this.getRow = __bind(this.getRow, this);
      this.getFields = __bind(this.getFields, this);
      this.setTimeRange = __bind(this.setTimeRange, this);
      this.setMaxVersions = __bind(this.setMaxVersions, this);
      this.addColumn = __bind(this.addColumn, this);
      this.tr = {
        from: null,
        to: null
      };
      this.familyMap = {};
      this.maxVersions = 1;
    }

    Get.prototype.addColumn = function(cf, qualifier) {
      var _base;
      if ((_base = this.familyMap)[cf] == null) {
        _base[cf] = [];
      }
      this.familyMap[cf].push(qualifier);
      return this;
    };

    Get.prototype.setMaxVersions = function(maxVersions) {
      if (maxVersions <= 0) {
        maxVersions = 1;
      }
      this.maxVersions = maxVersions;
      return this;
    };

    Get.prototype.setTimeRange = function(minStamp, maxStamp) {
      this.tr = {
        from: minStamp,
        to: maxStamp
      };
      return this;
    };

    Get.prototype.getFields = function() {
      var cf, o, qualifiers, _ref;
      o = {
        row: this.row,
        timeRange: this.tr,
        column: [],
        maxVersions: this.maxVersions
      };
      _ref = this.familyMap;
      for (cf in _ref) {
        qualifiers = _ref[cf];
        o.column = {
          family: cf,
          qualifier: qualifiers.map(function(qualifier) {
            return qualifier;
          })
        };
      }
      return o;
    };

    Get.prototype.getRow = function() {
      return this.row;
    };

    return Get;

  })();

}).call(this);
