// Generated by CoffeeScript 1.8.0
(function() {
  module.exports = {
    MAGIC: 255,
    MAGIC_SIZE: 1,
    ID_LENGTH_SIZE: 4,
    MD5_HEX_LENGTH: 32,
    SERVERNAME_SEPARATOR: ",",
    META_TABLE_NAME: new Buffer('hbase:meta'),
    META_REGION_NAME: new Buffer('hbase:meta,,1'),
    NINES: "99999999999999",
    ZEROS: "00000000000000",
    HEADER: new Buffer("HBas"),
    RPC_TIMEOUT: 30000,
    PING_TIMEOUT: 30000,
    CALL_TIMEOUT: 5000,
    SOCKET_RETRY_WAIT_MS: 200
  };

}).call(this);
