// Generated by CoffeeScript 1.8.0
(function() {
  module.exports = {
    bufferIncrement: (function(_this) {
      return function(buffer, i) {
        var b, newBuffer, tmp;
        b = new Buffer(buffer);
        if (i == null) {
          i = b.length - 1;
        }
        if (i < 0) {
          return Buffer.concat([new Buffer([1]), b]);
        }
        tmp = new Buffer([parseInt(b[i]++)]);
        if (tmp[0] > b[i]) {
          newBuffer = _this.bufferIncrement(b, i - 1);
        }
        if (newBuffer && b.length < newBuffer.length) {
          return newBuffer;
        }
        return b;
      };
    })(this),
    bufferCompare: function(a, b) {
      var i, len1, len2, _a, _b, _i, _ref;
      len1 = a.length;
      len2 = b.length;
      if (a === b && len1 === len2) {
        return 0;
      }
      for (i = _i = 0, _ref = len1 - 1; 0 <= _ref ? _i <= _ref : _i >= _ref; i = 0 <= _ref ? ++_i : --_i) {
        if (a[i] !== b[i]) {
          _a = a[i] ? a[i] : 0;
          _b = b[i] ? b[i] : 0;
          return _a - _b;
        }
      }
      return len1 - len2;
    }
  };

}).call(this);
